can tracable variable
XhmikosR/find-unused-sass-variables pull request #124
Opened 2021-01-29 23:34 UTC by danny007in

Breaking Change:

- Unused variables are grouped per files.
-  displayed with line and column

Highly helped by this PR https://github.com/XhmikosR/find-unused-sass-variables/pull/123

Co-Authored-By: Georg Gentzen <60478031+gentzeng@users.noreply.github.com>

2021-01-30 12:21 UTC, gentzeng commented
The variable $nestedVar belongs to test.scss

![issue](https://user-images.githubusercontent.com/60478031/106356197-0cbf2200-62fe-11eb-962b-b40783b3bd2d.png)

2021-01-30 12:44 UTC, gentzeng commented
@danny007in Is there some way to contact you?

2021-01-30 14:27 UTC, danny007in commented
> 
> 
> @danny007in Is there any way to contact you privately? (Before you fix the earlier mentioned bug ;) )

You can discuss here, so every can see wants going on this PR

2021-01-30 14:48 UTC, gentzeng commented
I like your Idea. However, if see it right, it introduces a quadratic runtime for setting the file paths. I incorporated your approach into PR #125 without that overhead, shrinked the code since your approach allows that and adjusted the results to be backwards compatible to not introduce a breaking change. Furthermore, I plan issue another pull request that is based on the current one.

Thanks for your valuable help :D

2021-01-30 14:49 UTC, gentzeng commented
For example, its easier to set the file path for each variable for creating reports in files, since, e.g., the SonarQube generic issues format requires that.

2021-01-31 15:52 UTC, gentzeng requested changes

2021-01-31 15:52 UTC, gentzeng commented on index.js
> +        });
This is introducing quadratic overhead and is hence inefficient. Just add the filename with the parse function in line 51 as I did in PR #125

2021-01-31 15:53 UTC, gentzeng commented on index.js
> +        });
Furthermore, as written above, its easier to set the file path for each variable for creating reports in files, since, e.g., the SonarQube generic issues format requires that.

2021-01-31 15:54 UTC, gentzeng commented
This is not a breaking change anymore. However, the Readme needs to be updated. You can find a version in PR #125, so you can save some time.

2021-01-31 16:50 UTC, closed without merging