feat: display tracking information about unused variables
XhmikosR/find-unused-sass-variables pull request #125
Opened 2021-01-30 14:44 UTC by gentzeng

**This is a feature and not a breaking change**

Unused variables are grouped per containig files and displayed with line
and column information. Files are displayed relatively to working
directory. In addition to total amount of variables, amount of unused
variables gets also displayed.

This feature incorporates ideas from PR #124.
Co-Authored-By: Daniel <50356015+danny007in@users.noreply.github.com>

2021-01-30 18:15 UTC, danny007in reviewed
did in  non feasible way plz check https://github.com/XhmikosR/find-unused-sass-variables/pull/124

2021-01-31 19:00 UTC, danny007in commented on tests/integration.js
> +    '$enabled-variable',
For this u needed Create another PR as improve all code

2021-01-31 19:15 UTC, danny007in requested changes

2021-01-31 19:15 UTC, danny007in commented on README.md
> +]
`]` to `// ]`

2021-01-31 19:15 UTC, danny007in commented on index.js
> +        // for backwards compatibility of API
give comment above `return {`

2021-01-31 19:15 UTC, danny007in commented on index.js
> +    // the number of occurences in sassFilesString
comment short and clearly

2021-01-31 19:15 UTC, danny007in commented on index.js
> +    const unusedVarsOrigin = variables.filter(variable => {
don't rename `unusedVars`

2021-01-31 19:15 UTC, danny007in commented on index.js
> +        unused: unusedVarsOrigin.map(({ name }) => name)
`unused` should above only, plz do not make more complicated code

2021-01-31 19:40 UTC, gentzeng commented on index.js
> +        unused: unusedVarsOrigin.map(({ name }) => name)
We need to keep the original 'unused' as an array containing only the variable names, as well as total being the amount of all variables, since I don't want to break the API of this function. Hence the additional return value for more information.

2021-01-31 19:48 UTC, gentzeng commented on README.md
> +]
Fixed

2021-01-31 19:48 UTC, gentzeng commented on index.js
> +        // for backwards compatibility of API
Fixed

2021-01-31 19:48 UTC, gentzeng commented on index.js
> +    // the number of occurences in sassFilesString
Fixed

2021-01-31 19:49 UTC, gentzeng commented on index.js
> +    const unusedVarsOrigin = variables.filter(variable => {
Fixed

2021-01-31 19:49 UTC, gentzeng commented on tests/integration.js
> +    '$enabled-variable',
Fixed

2021-01-31 19:51 UTC, gentzeng commented on index.js
> +        unused: unusedVarsOrigin.map(({ name }) => name)
Furthermore, I think its convenient to see not only the amount of all variables, but of the unused as well
![total](https://user-images.githubusercontent.com/60478031/106396092-1cc22900-6406-11eb-9a66-18efc4936461.png)

2021-01-31 20:02 UTC, danny007in approved these changes

2021-02-28 14:55 UTC, danny007in commented
@gentzeng rebase it

2021-03-03 17:27 UTC, gentzeng commented
Done

2021-03-06 13:49 UTC, danny007in commented on lib/parse-variable.js
> +function parseNodes(nodes, variables, ignoreList, file = '') {
carefully adapt this
https://github.com/XhmikosR/find-unused-sass-variables/pull/134#discussion_r588879445
for ` file = '') `

2021-09-15 14:15 UTC, closed without merging